apiVersion: apps/v1
kind: Deployment
metadata:
  name: rh-registry-gatekeeper-provider
  namespace: gatekeeper-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rh-registry-gatekeeper-provider
  template:
    metadata:
      labels:
        run: rh-registry-gatekeeper-provider
    spec:
      volumes:
        - name: volume-provider-certs
          secret:
            secretName: rh-registry-gatekeeper-provider-tls
            defaultMode: 420
        - name: volume-gatekeeper-certs
          secret:
            secretName: gatekeeper-webhook-server-cert
            defaultMode: 420
      containers:
      - image: quay.io/mooyeg/rh-registry-gatekeeper-provider:latest
        imagePullPolicy: Always
        name: rh-registry-gatekeeper-provider
        volumeMounts:
          - name: volume-gatekeeper-certs
            mountPath: /gatekeeper-ca
          - name: volume-provider-certs
            mountPath: /provider-certs
        ports:
        - containerPort: 8090
          protocol: TCP
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux