apiVersion: v1
kind: Service
metadata:
  name: rhreg-gkp-pro
  namespace: openshift-gatekeeper-system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rhreg-gkp-pro-tls
    #service.beta.openshift.io/inject-cabundle: "true"
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: rhreg-gkp-pro
  sessionAffinity: None