apiVersion: v1
kind: Service
metadata:
  name: rh-registry-gatekeeper-provider
  namespace: gatekeeper-system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rh-registry-gatekeeper-provider-tls
    service.beta.openshift.io/inject-cabundle: true
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: rh-registry-gatekeeper-provider
  sessionAffinity: None